# Generated by Django 4.2.1 on 2024-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0032_remove_equipo_idstatus_remove_equipo_idtipoequipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipos_contacto',
            field=models.CharField(choices=[['Consulta', 'Consulta'], ['Sugerencia', 'Sugerencia'], ['Problemas con tu cuenta', 'Problemas con tu cuenta']], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='datos_alumnos',
            name='carrera_Usuario',
            field=models.CharField(choices=[['Analista Programador Computacional', 'Analista Programador Computacional'], ['Contabilidad Tributaria', 'Contabilidad Tributaria'], ['Administración de Empresas', 'Administración de Empresas'], ['Desarrollo de Aplicaciones', 'Desarrollo de Aplicaciones'], ['ingeniería en Desarrollo de Software', 'ingeniería en Desarrollo de Software']], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postalumnos',
            name='tipo_post',
            field=models.IntegerField(choices=[[1, 'Grupo Estudio'], [2, 'Grupo Equipo'], [3, 'Grupo Ocio']]),
        ),
    ]
