# Generated by Django 5.0.3 on 2024-05-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0030_postalumnos_usuario_alter_datos_alumnos_correo_and_more'),
        ('appweb', '0033_alter_contacto_tipos_contacto_and_more'),
    ]

    operations = [
    ]
