# Generated by Django 5.0.3 on 2024-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0035_libros_remove_postalumnos_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='categoria',
            field=models.CharField(choices=[('tecnología', 'tecnología'), ('informática', 'informática'), ('Científicos', 'Científicos'), ('Matemáticas', 'Matemáticas'), ('Medicina', 'Medicina'), ('De referencia o consulta', 'De referencia o consulta'), ('Biografías', 'Biografías'), ('Literatura y lingüísticos', 'Literatura y lingüísticos')], max_length=50),
        ),
    ]
