# Generated by Django 5.0.3 on 2024-06-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0038_postalumnos_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalumnos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
